parameters:
  name: ''
  pool: ''
  platform: ''
  sign: false

jobs:
  - job: ${{ parameters.name }}
    pool: ${{ parameters.pool }}
    steps:
      - task: Gradle@2
        inputs:
          gradleWrapperFile: 'gradlew'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          tasks: 'dist'
          options: '-Pplatform=${{ parameters.platform }}'
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(System.DefaultWorkingDirectory)/build/milo-demo-server-${{ parameters.platform }}.zip'