trigger:
  - master

# don't trigger this pipeline on PRs
pr: none

jobs:
  # Linux job
  - template: image-builder-template.yml
    parameters:
      name: Linux
      platform: linux
      pool:
        vmImage: 'ubuntu-20.04'

  # Mac OS job
  - template: image-builder-template.yml
    parameters:
      name: MacOS
      platform: mac
      pool:
        vmImage: 'macOS-11'

  # Windows job
  - template: image-builder-template.yml
    parameters:
      name: Windows
      platform: win
      pool:
        vmImage: 'windows-2019'
